<a href="https://colab.research.google.com/github/matgonzalez23/MetNumUN2022I/blob/main/Lab_2/matgonzalez_ScottsSanderson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%matplotlib inline
%load_ext fortranmagic

import sys; sys.path.append('..')

import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

mpl.rc('figure', figsize=(12, 7))

ran_the_first_cell = True

jan2017 = pd.to_datetime(['2017-01-03 00:00:00+00:00',
 '2017-01-04 00:00:00+00:00',
 '2017-01-05 00:00:00+00:00',
 '2017-01-06 00:00:00+00:00',
 '2017-01-09 00:00:00+00:00',
 '2017-01-10 00:00:00+00:00',
 '2017-01-11 00:00:00+00:00',
 '2017-01-12 00:00:00+00:00',
 '2017-01-13 00:00:00+00:00',
 '2017-01-17 00:00:00+00:00',
 '2017-01-18 00:00:00+00:00',
 '2017-01-19 00:00:00+00:00',
 '2017-01-20 00:00:00+00:00',
 '2017-01-23 00:00:00+00:00',
 '2017-01-24 00:00:00+00:00',
 '2017-01-25 00:00:00+00:00',
 '2017-01-26 00:00:00+00:00',
 '2017-01-27 00:00:00+00:00',
 '2017-01-30 00:00:00+00:00',
 '2017-01-31 00:00:00+00:00',
 '2017-02-01 00:00:00+00:00'])
calendar = jan2017.values.astype('datetime64[D]')

event_dates = pd.to_datetime(['2017-01-06 00:00:00+00:00', 
                             '2017-01-07 00:00:00+00:00', 
                             '2017-01-08 00:00:00+00:00']).values.astype('datetime64[D]')
event_values = np.array([10, 15, 20])

The fortranmagic extension is already loaded. To reload it, use:
  %reload_ext fortranmagic


# Lists

In [ ]:
l=[1, 'two', 3.0, 4, 5.0, "six"]
l

[1, 'two', 3.0, 4, 5.0, 'six']

In [ ]:
l2=[11, 'twelve', 13.0, 14, 15.0, "sixteen", 'seventeen']
l2

[11, 'twelve', 13.0, 14, 15.0, 'sixteen', 'seventeen']

In [ ]:
first = l[0]
second = l[1]
print("first:", first)
print("second:", second)

first: 1
second: two


In [ ]:
third = l2[2]
fourth = l2[5]
print("third:", third)
print("fourth:", fourth)

third: 13.0
fourth: sixteen


In [ ]:
last = l[-1]
penultimate = l[-2]
print("last:", last)
print("second to last:", penultimate)

last: six
second to last: 5.0


In [ ]:
last = l2[-1]
penultimate = l2[-2]
print("last:", last)
print("second to last:", penultimate)

last: seventeen
second to last: sixteen


In [ ]:
sublist = l[1:3]
sublist

['two', 3.0]

In [ ]:
sublist = l2[0:4]
sublist

[11, 'twelve', 13.0, 14]

In [ ]:
first_three = l[:3]
first_three

[1, 'two', 3.0]

In [ ]:
first_two = l2[:2]
first_two

[11, 'twelve']

In [ ]:
after_three = l[3:]
after_three

[4, 5.0, 'six']

In [ ]:
after_two = l2[2:]
after_two

[13.0, 14, 15.0, 'sixteen', 'seventeen']

In [ ]:
l = ['a', 'b', 'c', 'd', 'e', 'f', 'g','h']
l[1:7:2]

['b', 'd', 'f']

In [ ]:
l2 = ['i', 'j', 'k', 'l', 'm', 'n', 'ñ','o']
l2[0:6:3]

['i', 'l']

In [ ]:
l[::-1]

['h', 'g', 'f', 'e', 'd', 'c', 'b', 'a']

In [ ]:
l2[::-1]

['o', 'ñ', 'n', 'm', 'l', 'k', 'j', 'i']

In [ ]:
l = [1, 2, 3, 4, 5]
print("Before:", l)
l.append('six')
print("After:", l)

Before: [1, 2, 3, 4, 5]
After: [1, 2, 3, 4, 5, 'six']


In [ ]:
l2 = [6, 7, 8, 9, 10]
print("Before:", l2)
l2.append('eleven')
print("After:", l2)

Before: [6, 7, 8, 9, 10]
After: [6, 7, 8, 9, 10, 'eleven']


In [ ]:
l = [1, 2, 3, 4, 5]
[x * 2 for x in l]

[2, 4, 6, 8, 10]

In [ ]:
l2 = [6, 7, 8, 9, 10]
[x * 5 for x in l2]

[30, 35, 40, 45, 50]

# Dictionaries

In [ ]:
philosophers = {'David': 'Hume', 'Immanuel': 'Kant', 'Bertrand': 'Russell'}
philosophers

{'Bertrand': 'Russell', 'David': 'Hume', 'Immanuel': 'Kant'}

In [ ]:
Basketball_Players = {'Jimmy': 'Butler', 'Lebron': 'James', 'Chris': 'Paul'}
Basketball_Players

{'Chris': 'Paul', 'Jimmy': 'Butler', 'Lebron': 'James'}

In [ ]:
philosophers['Ludwig'] = 'Wittgenstein'
philosophers

{'Bertrand': 'Russell',
 'David': 'Hume',
 'Immanuel': 'Kant',
 'Ludwig': 'Wittgenstein'}

In [ ]:
Basketball_Players['James'] = 'Harden'
Basketball_Players

{'Chris': 'Paul', 'James': 'Harden', 'Jimmy': 'Butler', 'Lebron': 'James'}

In [ ]:
del philosophers['David']
philosophers

{'Bertrand': 'Russell', 'Immanuel': 'Kant', 'Ludwig': 'Wittgenstein'}

In [ ]:
del Basketball_Players['Jimmy']
Basketball_Players

{'Chris': 'Paul', 'James': 'Harden', 'Lebron': 'James'}

In [ ]:
# No slicing.
philosophers['Bertrand':'Immanuel']

# Matrices

In [ ]:
# Suppose we have some matrices...
a = [[1, 2, 3],
     [2, 3, 4],
     [5, 6, 7],
     [1, 1, 1]]

b = [[1, 2, 3, 4],
     [2, 3, 4, 5]]

In [ ]:
# Suppose we have some matrices...
c = [[5, 2, 9],
     [2, 8, 0],
     [5, 7, 7],
     [4, 4, 4]]

d = [[3, 4, 5, 6],
     [6, 2, 8, 9]]

In [ ]:
def matmul(A, B):
    """Multiply matrix A by matrix B."""
    rows_out = len(A)
    cols_out = len(B[0])
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]
    
    for i in range(rows_out):
        for j in range(cols_out):
            for k in range(len(B)):
                out[i][j] += A[i][k] * B[k][j]
    return out

In [ ]:
def matmul(C, D):
    """Multiply matrix A by matrix B."""
    rows_out = len(C)
    cols_out = len(D[0])
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]
    
    for i in range(rows_out):
        for j in range(cols_out):
            for k in range(len(D)):
                out[i][j] += C[i][k] * D[k][j]
    return out

In [ ]:
%%time

matmul(a, b)

CPU times: user 25 µs, sys: 3 µs, total: 28 µs
Wall time: 32.2 µs


[[5, 8, 11, 14], [8, 13, 18, 23], [17, 28, 39, 50], [3, 5, 7, 9]]

In [ ]:
%%time

matmul(c, d)

CPU times: user 0 ns, sys: 38 µs, total: 38 µs
Wall time: 42 µs


[[27, 24, 41, 48], [54, 24, 74, 84], [57, 34, 81, 93], [36, 24, 52, 60]]

In [ ]:
import random
def random_matrix(m, n):
    out = []
    for row in range(m):
        out.append([random.random() for _ in range(n)])
    return out

randm = random_matrix(2, 3)
randm

[[0.07461407993733538, 0.5464035628324863, 0.9522762148112138],
 [0.5223889852566403, 0.9181128491603435, 0.829369776689268]]

In [ ]:
import random
def random_matrix(m, n):
    out = []
    for row in range(m):
        out.append([random.random() for _ in range(n)])
    return out

randm2 = random_matrix(3, 4)
randm2

[[0.779800499386015,
  0.290510523145873,
  0.05083155931527095,
  0.061677567518142795],
 [0.5608085982789891,
  0.27864212511456243,
  0.6591222591627338,
  0.6119135325693293],
 [0.5684367357997278,
  0.6135408985200865,
  0.7380313826082783,
  0.8496596462074218]]

In [ ]:
%%time
randa = random_matrix(600, 100)
randb = random_matrix(100, 600)
x = matmul(randa, randb)

CPU times: user 10.6 s, sys: 2.89 ms, total: 10.6 s
Wall time: 10.7 s


In [ ]:
%%time
randa = random_matrix(50, 75)
randb = random_matrix(75, 50)
x = matmul(randa, randb)

CPU times: user 54.8 ms, sys: 916 µs, total: 55.8 ms
Wall time: 56.6 ms


In [ ]:
def python_dot_product(xs, ys):
    return sum(x * y for x, y in zip(xs, ys))

In [ ]:
!pip install -U fortran-magic

In [ ]:
%reload_ext fortranmagic

/usr/local/lib/python3.7/dist-packages/fortranmagic.py:147: UserWarning: get_ipython_cache_dir has moved to the IPython.paths module since IPython 4.0.
  self._lib_dir = os.path.join(get_ipython_cache_dir(), 'fortran')


In [ ]:
%%fortran

subroutine fortran_dot_product(xs, ys, result)
    double precision, intent(in) :: xs(:)
    double precision, intent(in) :: ys(:)
    double precision, intent(out) :: result
    
    result = sum(xs * ys)
end

In [ ]:
list_data = [float(i) for i in range(100000)]
array_data = np.array(list_data)

In [ ]:
list_data2 = [float(i) for i in range(75000)]
array_data2 = np.array(list_data2)

In [ ]:
%%time
python_dot_product(list_data, list_data)

CPU times: user 10.2 ms, sys: 872 µs, total: 11.1 ms
Wall time: 13.2 ms


333328333350000.0

In [ ]:
%%time
python_dot_product(list_data2, list_data2)

CPU times: user 8.8 ms, sys: 0 ns, total: 8.8 ms
Wall time: 8.82 ms


140622187512500.0

In [ ]:
%%time
fortran_dot_product(array_data2, array_data2)

CPU times: user 132 µs, sys: 10 µs, total: 142 µs
Wall time: 150 µs


140622187512500.0

# Why is the Python Version so Much Slower?

In [ ]:
# Dynamic typing.
def mul_elemwise(xs, ys):
    return [x * y for x, y in zip(xs, ys)]

mul_elemwise([1, 2, 3, 4], [1, 2 + 0j, 3.0, 'four'])
#[type(x) for x in _]

[1, (4+0j), 9.0, 'fourfourfourfour']

In [ ]:
source_code = 'a + b * c'
bytecode = compile(source_code, '', 'eval')
import dis; dis.dis(bytecode)

  1           0 LOAD_NAME                0 (a)
              2 LOAD_NAME                1 (b)
              4 LOAD_NAME                2 (c)
              6 BINARY_MULTIPLY
              8 BINARY_ADD
             10 RETURN_VALUE


# Why is the Python Version so Slow?


*   Dynamic typing means that every single operation requires dispatching on the input type.
*   Having an interpreter means that every instruction is fetched and dispatched at runtime
*   Other overheads
  *   Arbitrary-size integers.
  *   Reference-counted garbage collection.
*   Jake VanderPlas, Losing Your Loops: Fast Numerical Computing with NumPy



# What do we do?


*   Python is slow for numerical computation because it performs dynamic dispatch on every operation we perform...
*   ...but often, we just want to do the same thing over and over in a loop!
*   If we don't need Python's dynamicism, we don't want to pay (much) for it.
Idea: Dispatch once per operation instead of once per element.







In [ ]:
import numpy as np

data = np.array([1, 2, 3, 4])
data

array([1, 2, 3, 4])

In [ ]:
data2 = np.array([5, 6, 7, 8])
data2

array([5, 6, 7, 8])

In [ ]:
data + data

array([2, 4, 6, 8])

In [ ]:
data2 + data2

array([10, 12, 14, 16])

In [ ]:
%%time
# Naive dot product
(array_data * array_data).sum()

CPU times: user 1.15 ms, sys: 1.06 ms, total: 2.2 ms
Wall time: 1.6 ms


333328333350000.0

In [ ]:
%%time
# Naive dot product
(array_data2 * array_data2).sum()

CPU times: user 335 µs, sys: 25 µs, total: 360 µs
Wall time: 373 µs


140622187512500.0

In [ ]:
%%time
# Built-in dot product.
array_data.dot(array_data)

CPU times: user 878 µs, sys: 875 µs, total: 1.75 ms
Wall time: 1.07 ms


333328333350000.0

In [ ]:
%%time
# Built-in dot product.
array_data2.dot(array_data2)

CPU times: user 812 µs, sys: 959 µs, total: 1.77 ms
Wall time: 1.74 ms


140622187512500.0

In [ ]:
%%time
fortran_dot_product(array_data, array_data)

CPU times: user 212 µs, sys: 0 ns, total: 212 µs
Wall time: 220 µs


333328333350000.0

In [ ]:
%%time
fortran_dot_product(array_data2, array_data2)

CPU times: user 138 µs, sys: 12 µs, total: 150 µs
Wall time: 156 µs


140622187512500.0

In [ ]:
# We **can** reshape an array though.
two_by_two = data.reshape(2, 2)
two_by_two

array([[1, 2],
       [3, 4]])

Numpy arrays are:

* Fixed-type
* Size-immutable
* Multi-dimensional
* Fast
*If you use them correctly.

# What's in an Array?

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6], dtype='int16').reshape(2, 3)
print("Array:\n", arr, sep='')
print("===========")
print("DType:", arr.dtype)
print("Shape:", arr.shape)
print("Strides:", arr.strides)
print("Data:", arr.data.tobytes())

Array:
[[1 2 3]
 [4 5 6]]
DType: int16
Shape: (2, 3)
Strides: (6, 2)
Data: b'\x01\x00\x02\x00\x03\x00\x04\x00\x05\x00\x06\x00'


In [ ]:
arr2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int16').reshape(3, 3)
print("Array:\n", arr2, sep='')
print("===========")
print("DType:", arr2.dtype)
print("Shape:", arr2.shape)
print("Strides:", arr2.strides)
print("Data:", arr2.data.tobytes())

Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
DType: int16
Shape: (3, 3)
Strides: (6, 2)
Data: b'\x01\x00\x02\x00\x03\x00\x04\x00\x05\x00\x06\x00\x07\x00\x08\x00\t\x00'


# Core Operations
* Vectorized ufuncs for elementwise operations.
* Fancy indexing and masking for selection and filtering.
* Aggregations across axes.
* Broadcasting

# UFuncs
UFuncs (universal functions) are functions that operate elementwise on one or more arrays.

In [ ]:
data = np.arange(15).reshape(3, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
data2 = np.arange(20).reshape(5, 4)
data2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
# Binary operators.
data * data

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

In [ ]:
# Binary operators.
data2 * data2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225],
       [256, 289, 324, 361]])

In [ ]:
# Unary functions.
np.sqrt(data)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739]])

In [ ]:
# Unary functions.
np.sqrt(data2)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894]])

In [ ]:
# Comparison operations
(data % 3) == 0

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False]])

In [ ]:
# Comparison operations
(data2 % 5) == 0

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True],
       [False, False, False, False]])

In [ ]:
# Boolean combinators.
((data % 2) == 0) & ((data % 3) == 0)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False]])

In [ ]:
((data2 % 4) == 0) & ((data2 % 5) == 0)

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# as of python 3.5, @ is matrix-multiply
data @ data.T

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [ ]:
data2 @ data2.T

array([[  14,   38,   62,   86,  110],
       [  38,  126,  214,  302,  390],
       [  62,  214,  366,  518,  670],
       [  86,  302,  518,  734,  950],
       [ 110,  390,  670,  950, 1230]])

# Selections

In [ ]:
sines = np.sin(np.linspace(0, 3.14, 10))
cosines = np.cos(np.linspace(0, 3.14, 10))
sines

array([0.        , 0.34185385, 0.64251645, 0.86575984, 0.98468459,
       0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

In [ ]:
sines = np.sin(np.linspace(0, 3.14, 10))
cosines = np.cos(np.linspace(0, 3.1416, 10))
cosines

array([ 1.        ,  0.93969234,  0.76604339,  0.49999788,  0.17364496,
       -0.1736522 , -0.50000424, -0.76604812, -0.93969485, -1.        ])

In [ ]:
sines[0]

0.0

In [ ]:
cosines[3]

0.5004596890082056

In [ ]:
sines[:3]

array([0.        , 0.34185385, 0.64251645])

In [ ]:
cosines[:5]

array([1.        , 0.93969234, 0.76604339, 0.49999788, 0.17364496])

In [ ]:
sines[5:] 

array([0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

In [ ]:
cosines[5:] 

array([-0.1736522 , -0.50000424, -0.76604812, -0.93969485, -1.        ])

In [ ]:
sines[::2]

array([0.        , 0.64251645, 0.98468459, 0.8665558 , 0.34335012])

In [ ]:
cosines[::2]

array([ 1.        ,  0.76604339,  0.17364496, -0.50000424, -0.93969485])

In [ ]:
# More interesting: we can index with boolean arrays to filter by a predicate.
print("sines:\n", sines)
print("sines > 0.5:\n", sines > 0.5)
print("sines[sines > 0.5]:\n", sines[sines > 0.5])

sines:
 [0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]
sines > 0.5:
 [False False  True  True  True  True  True  True False False]
sines[sines > 0.5]:
 [0.64251645 0.86575984 0.98468459 0.98496101 0.8665558  0.64373604]


In [ ]:
# More interesting: we can index with boolean arrays to filter by a predicate.
print("cosines:\n", cosines)
print("cosines > 0.5:\n", cosines > 0.5)
print("cosines[cosines > 0.5]:\n", cosines[cosines > 0.5])

cosines:
 [ 1.          0.93969234  0.76604339  0.49999788  0.17364496 -0.1736522
 -0.50000424 -0.76604812 -0.93969485 -1.        ]
cosines > 0.5:
 [ True  True  True False False False False False False False]
cosines[cosines > 0.5]:
 [1.         0.93969234 0.76604339]


In [ ]:
# We index with lists/arrays of integers to select values at those indices.
print(sines)
sines[[0, 4, 7]]

[0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]


array([0.        , 0.98468459, 0.64373604])

In [ ]:
# We index with lists/arrays of integers to select values at those indices.
print(cosines)
cosines[[0, 2, 5]]

[ 1.          0.93969234  0.76604339  0.49999788  0.17364496 -0.1736522
 -0.50000424 -0.76604812 -0.93969485 -1.        ]


array([ 1.        ,  0.76604339, -0.1736522 ])

In [ ]:
# Index arrays are often used for sorting one or more arrays.
unsorted_data = np.array([1, 3, 2, 12, -1, 5, 2])

In [ ]:
unsorted_data2 = np.array([2, 1, 5, 9, -1, 3, 1])

In [ ]:
sort_indices = np.argsort(unsorted_data)
sort_indices

array([4, 0, 2, 6, 1, 5, 3])

In [ ]:
sort_indices2 = np.argsort(unsorted_data2)
sort_indices2

array([4, 1, 6, 0, 5, 2, 3])

In [ ]:
unsorted_data[sort_indices]

array([-1,  1,  2,  2,  3,  5, 12])

In [ ]:
unsorted_data2[sort_indices2]

array([-1,  1,  1,  2,  3,  5,  9])

In [ ]:
market_caps = np.array([12, 6, 10, 5, 6])  # Presumably in dollars?
assets = np.array(['A', 'B', 'C', 'D', 'E'])

In [ ]:
market_caps2 = np.array([9, 11, 4, 7, 3])
assets2 = np.array(['A', 'B', 'C', 'D', 'E'])

In [ ]:
# Sort assets by market cap by using the permutation that would sort market caps on ``assets``.
sort_by_mcap = np.argsort(market_caps)
assets[sort_by_mcap]

array(['D', 'B', 'E', 'C', 'A'], dtype='<U1')

In [ ]:
sort_by_mcap2 = np.argsort(market_caps2)
assets2[sort_by_mcap2]

array(['E', 'C', 'D', 'A', 'B'], dtype='<U1')

In [ ]:
# Indexers are also useful for aligning data.
print("Dates:\n", repr(event_dates))
print("Values:\n", repr(event_values))
print("Calendar:\n", repr(calendar))

Dates:
 array(['2017-01-06', '2017-01-07', '2017-01-08'], dtype='datetime64[D]')
Values:
 array([10, 15, 20])
Calendar:
 array(['2017-01-03', '2017-01-04', '2017-01-05', '2017-01-06',
       '2017-01-09', '2017-01-10', '2017-01-11', '2017-01-12',
       '2017-01-13', '2017-01-17', '2017-01-18', '2017-01-19',
       '2017-01-20', '2017-01-23', '2017-01-24', '2017-01-25',
       '2017-01-26', '2017-01-27', '2017-01-30', '2017-01-31',
       '2017-02-01'], dtype='datetime64[D]')


In [ ]:
print("Raw Dates:", event_dates)
print("Indices:", calendar.searchsorted(event_dates))
print("Forward-Filled Dates:", calendar[calendar.searchsorted(event_dates)])

Raw Dates: ['2017-01-06' '2017-01-07' '2017-01-08']
Indices: [3 4 4]
Forward-Filled Dates: ['2017-01-06' '2017-01-09' '2017-01-09']


In [ ]:
data = np.arange(25).reshape(5, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
data2 = np.arange(18).reshape(6, 3)
data2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
data[:2, :2]  # First two rows and first two columns.


array([[0, 1],
       [5, 6]])

In [ ]:
data2[:3, :1] 

array([[0],
       [4],
       [8]])

In [ ]:
data[:2, [0, -1]]  # First two rows, first and last columns.

array([[0, 4],
       [5, 9]])

In [ ]:
data2[:5, [0, -1]]

array([[ 0,  3],
       [ 4,  7],
       [ 8, 11],
       [12, 15],
       [16, 19]])

In [ ]:
data[(data[:, 0] % 2) == 0]  # Rows where the first column is divisible by two

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [ ]:
data2[(data2[:, 1] % 3) == 0]

array([[ 8,  9, 10, 11]])

# Reductions
Functions that reduce an array to a scalar.

 


In [ ]:
def variance(x):
    return ((x - x.mean()) ** 2).sum() / len(x)

In [ ]:
variance(np.random.standard_normal(1000))

0.9889274415627579

In [ ]:
variance(np.random.standard_normal(500))

1.065491865731497

In [ ]:
data = np.arange(30)
data.mean()

14.5

In [ ]:
data2 = np.arange(15)
data2.mean()

7.0

In [ ]:
data = np.arange(30).reshape(3, 10)
data

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
data2 = np.arange(15).reshape(5, 3)
data2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
data.mean()

14.5

In [ ]:
data2.mean()

7.0

In [ ]:
data.mean(axis=0)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [ ]:
data2.mean(axis=1)

array([ 1.,  4.,  7., 10., 13.])

# Broadcasting

In [ ]:
row = np.array([1, 2, 3, 4])
column = np.array([[1], [2], [3]])
print("Row:\n", row, sep='')
print("Column:\n", column, sep='')

Row:
[1 2 3 4]
Column:
[[1]
 [2]
 [3]]


In [ ]:
row2 = np.array([6, 7, 8, 9])
column2 = np.array([[6], [7], [8]])
print("Row:\n", row, sep='')
print("Column:\n", column, sep='')

Row:
[6 7 8 9]
Column:
[[6]
 [7]
 [8]]


In [ ]:
row + column

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [ ]:
row2 + column2

array([[12, 13, 14, 15],
       [13, 14, 15, 16],
       [14, 15, 16, 17]])

In [ ]:
# Broadcasting is particularly useful in conjunction with reductions.
print("Data:\n", data, sep='')
print("Mean:\n", data.mean(axis=0), sep='')
print("Data - Mean:\n", data - data.mean(axis=0), sep='')

Data:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
Mean:
[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
Data - Mean:
[[-10. -10. -10. -10. -10. -10. -10. -10. -10. -10.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 10.  10.  10.  10.  10.  10.  10.  10.  10.  10.]]


In [ ]:
# Broadcasting is particularly useful in conjunction with reductions.
print("Data:\n", data2, sep='')
print("Mean:\n", data2.mean(axis=0), sep='')
print("Data - Mean:\n", data2 - data2.mean(axis=0), sep='')

Data:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
Mean:
[6. 7. 8.]
Data - Mean:
[[-6. -6. -6.]
 [-3. -3. -3.]
 [ 0.  0.  0.]
 [ 3.  3.  3.]
 [ 6.  6.  6.]]


# Numpy Review
* Numerical algorithms are slow in pure Python because the overhead dynamic dispatch dominates our runtime.
* Numpy solves this problem by:
  1. Imposing additional restrictions on the contents of arrays.
  2. Moving the inner loops of our algorithms into compiled C code.
* Using Numpy effectively often requires reworking an algorithms to use vectorized operations instead of for-loops, but the resulting operations are usually simpler, clearer, and faster than the pure Python equivalent.

# Selection in Pandas

In [ ]:
s = pd.Series(index=['a', 'b', 'c', 'd', 'e'], data=[1, 2, 3, 4, 5])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
w = pd.Series(index=['i', 'ii', 'iii', 'iv', 'v'], data=[5, 10, 15, 20, 25])
w

i       5
ii     10
iii    15
iv     20
v      25
dtype: int64

In [ ]:
# There are two pieces to a Series: the index and the values.
print("The index is:", s.index)
print("The values are:", s.values)

The index is: Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
The values are: [1 2 3 4 5]


In [ ]:
print("The index is:", w.index)
print("The values are:", w.values)

The index is: Index(['i', 'ii', 'iii', 'iv', 'v'], dtype='object')
The values are: [ 5 10 15 20 25]


In [ ]:
# We can look up values out of a Series by position...
s.iloc[0]

1

In [ ]:
w.iloc[2]

15

In [ ]:
# ... or by label.
s.loc['a']

1

In [ ]:
w.loc['iii']

15

In [ ]:
# Slicing works as expected...
s.iloc[:2]

a    1
b    2
dtype: int64

In [ ]:
w.iloc[:3]

i       5
ii     10
iii    15
dtype: int64

In [ ]:
# ...but it works with labels too!
s.loc[:'c']

a    1
b    2
c    3
dtype: int64

In [ ]:
w.loc[:'iv']

i       5
ii     10
iii    15
iv     20
dtype: int64

In [ ]:
# Fancy indexing works the same as in numpy.
s.iloc[[0, -1]]

a    1
e    5
dtype: int64

In [ ]:
w.iloc[[1, -2]]

ii    10
iv    20
dtype: int64

In [ ]:
# As does boolean masking.
s.loc[s > 2]

c    3
d    4
e    5
dtype: int64

In [ ]:
w.loc[w>15]

iv    20
v     25
dtype: int64

In [ ]:
# Element-wise operations are aligned by index.
other_s = pd.Series({'a': 10.0, 'c': 20.0, 'd': 30.0, 'z': 40.0})
other_s

a    10.0
c    20.0
d    30.0
z    40.0
dtype: float64

In [ ]:
other_w = pd.Series({'x': 5.0, 'ii': 50.0, 'z': 500.0, 'v': 5000.0})
other_w

x        5.0
ii      50.0
z      500.0
v     5000.0
dtype: float64

In [ ]:
s + other_s

a    11.0
b     NaN
c    23.0
d    34.0
e     NaN
z     NaN
dtype: float64

In [ ]:
w + other_w

i         NaN
ii       60.0
iii       NaN
iv        NaN
v      5025.0
x         NaN
z         NaN
dtype: float64

In [ ]:
# We can fill in missing values with fillna().
(s + other_s).fillna(0.0)

a    11.0
b     0.0
c    23.0
d    34.0
e     0.0
z     0.0
dtype: float64

In [ ]:
(w + other_w).fillna(0.0)

i         0.0
ii       60.0
iii       0.0
iv        0.0
v      5025.0
x         0.0
z         0.0
dtype: float64

# Pandas Review
* Pandas extends numpy with more complex datastructures and algorithms.
* If you understand numpy, you understand 90% of pandas.
groupby, set_index, and unstack are powerful tools for working with categorical data.
* Avocado prices are surprisingly interesting :)
# Thanks!